/**
 * API layer for MIK for Kids.
 *
 * The app was rebuilt from its deployed frontend after the original Convex
 * project access was lost. The full API contract was recovered from the
 * production bundles, and is implemented twice:
 *
 *  1. `mock` (default): a localStorage-backed backend so the app runs with no
 *     infrastructure at all. Ideal for local development and demos.
 *  2. `convex`: real Convex queries/mutations against the functions in
 *     `convex/` (surahs + content modules), with auth served by Convex Auth
 *     (guest + email-OTP).
 *
 * Select with VITE_BACKEND=convex and VITE_CONVEX_URL=https://<deployment>.convex.cloud
 */

import { useCallback, useEffect, useRef, useState } from "react";
import { backendKind, getConvexHttpClient } from "./backend-client";
import { convexAuth } from "./convex-auth";
import { api } from "../../convex/_generated/api"; // real one, generated by `npx convex dev`
import {
  mockAuth,
  mockComments,
  mockContent,
  mockProgress,
  mockQuizzes,
  mockSurahs,
  notifyStoreChange,
  subscribeToStore,
} from "./mock-backend";
import type {
  AuthUser,
  Comment,
  PracticedRecord,
  QuizBest,
  QuizSummary,
  Recording,
  Surah,
} from "./types";

// ---------------------------------------------------------------------------
// The API surface used by the UI
// ---------------------------------------------------------------------------

export interface MikApi {
  // auth
  getUser(): Promise<AuthUser | null>;
  signInAnonymous(): Promise<AuthUser>;
  requestEmailOtp(email: string): Promise<void>;
  verifyEmailOtp(code: string, email?: string): Promise<AuthUser>;
  signOut(): Promise<void>;
  // quran
  listSurahs(): Promise<Surah[]>;
  getSurah(number: number): Promise<Surah | null>;
  seedSurahList(): Promise<void>;
  seedSurah(args: { number: number }): Promise<void>;
  // progress
  listPracticed(): Promise<PracticedRecord[]>;
  togglePracticed(args: {
    surahNumber: number;
    ayahNumber: number;
  }): Promise<void>;
  // recordings
  myRecordings(): Promise<Recording[]>;
  courseRecordings(args: { surahNumber: number }): Promise<Recording[]>;
  generateUploadUrl(): Promise<string>;
  saveRecording(input: {
    storageId?: string;
    title: string;
    description?: string;
    surahNumber?: number;
    ayahNumber?: number;
    audioDataUrl?: string;
  }): Promise<string>;
  deleteRecording(args: { id: string }): Promise<void>;
  // comments
  listComments(args: {
    targetType: string;
    targetId: string;
  }): Promise<Comment[]>;
  addComment(args: {
    targetType: string;
    targetId: string;
    text: string;
  }): Promise<void>;
  // quizzes
  quizBest(args: { surahNumber: number }): Promise<QuizBest | null>;
  quizSummary(): Promise<QuizSummary>;
  saveQuizResult(args: {
    surahNumber: number;
    score: number;
    total: number;
  }): Promise<void>;
}

const convexApi: MikApi = {
  getUser: () => convexAuth.getUser(),
  signInAnonymous: () => convexAuth.signInAnonymous(),
  requestEmailOtp: (email) => convexAuth.requestEmailOtp(email),
  verifyEmailOtp: (code, email) => convexAuth.verifyEmailOtp(code, email),
  signOut: () => convexAuth.signOut(),

  async listSurahs() {
    const rows = await getConvexHttpClient().query(api.surahs.list, {});
    return rows as unknown as Surah[];
  },
  async getSurah(number) {
    const res = await getConvexHttpClient().query(api.surahs.getSurah, {
      number,
    });
    return res ? (res.surah as unknown as Surah) : null;
  },
  async seedSurahList() {
    await getConvexHttpClient().action(api.surahs.seedSurahList, {});
  },
  async seedSurah(args) {
    await getConvexHttpClient().action(api.surahs.seedSurah, args);
  },

  async listPracticed() {
    return getConvexHttpClient().query(api.surahs.listPracticed, {});
  },
  async togglePracticed(args) {
    await getConvexHttpClient().mutation(api.surahs.toggleAyahPracticed, args);
    notifyStoreChange();
  },

  async myRecordings() {
    const rows = await getConvexHttpClient().query(api.content.myRecordings, {});
    return rows as unknown as Recording[];
  },
  async courseRecordings(args) {
    const rows = await getConvexHttpClient().query(
      api.content.courseRecordings,
      args,
    );
    return rows as unknown as Recording[];
  },
  async generateUploadUrl() {
    return getConvexHttpClient().mutation(api.content.generateUploadUrl, {});
  },
  async saveRecording(input) {
    // Cast at the boundary: the UI passes plain strings; the generated API
    // expects Convex's branded Id types.
    const id = await getConvexHttpClient().mutation(
      api.content.saveRecording,
      input as any,
    );
    return id as unknown as string;
  },
  async deleteRecording(args) {
    await getConvexHttpClient().mutation(api.content.deleteRecording, {
      id: args.id as any,
    });
    notifyStoreChange();
  },

  async listComments(args) {
    const rows = await getConvexHttpClient().query(api.content.comments, args);
    return rows as unknown as Comment[];
  },
  async addComment(args) {
    await getConvexHttpClient().mutation(api.content.addComment, args);
    notifyStoreChange();
  },

  async quizBest(args) {
    const row = await getConvexHttpClient().query(api.content.quizBest, args);
    return row ? { score: row.score, total: row.total } : null;
  },
  async quizSummary() {
    const res = await getConvexHttpClient().query(api.content.quizSummary, {});
    return {
      taken: res.taken,
      best: res.best
        ? { score: res.best.score, total: res.best.total }
        : undefined,
    };
  },
  async saveQuizResult(args) {
    await getConvexHttpClient().mutation(api.content.saveQuizResult, args);
    notifyStoreChange();
  },
};

const mockApi: MikApi = {
  getUser: () => mockAuth.getUser(),
  signInAnonymous: () => mockAuth.signInAnonymous(),
  requestEmailOtp: (email) => mockAuth.requestEmailOtp(email),
  verifyEmailOtp: (code, email) => mockAuth.verifyEmailOtp(code, email),
  signOut: () => mockAuth.signOut(),

  listSurahs: () => mockSurahs.list(),
  getSurah: (number) => mockSurahs.getSurah(number),
  seedSurahList: () => mockSurahs.seedSurahList(),
  seedSurah: (args) => mockSurahs.seedSurah(args),

  listPracticed: () => mockProgress.list(),
  togglePracticed: (args) => mockProgress.toggle(args),

  myRecordings: () => mockContent.myRecordings(),
  courseRecordings: (args) => mockContent.courseRecordings(args),
  generateUploadUrl: () => mockContent.generateUploadUrl(),
  saveRecording: (input) => mockContent.saveRecording(input),
  deleteRecording: (args) => mockContent.deleteRecording(args),

  listComments: (args) => mockComments.list(args),
  addComment: (args) => mockComments.addComment(args),

  quizBest: (args) => mockQuizzes.best(args),
  quizSummary: () => mockQuizzes.summary(),
  saveQuizResult: (args) => mockQuizzes.save(args),
};

export const backend: MikApi = backendKind === "convex" ? convexApi : mockApi;

// Initialize the auth bridge (restores a persisted Convex session if any).
if (backendKind === "convex") convexAuth.init();

// ---------------------------------------------------------------------------
// Tiny React binding helpers (useQuery/useMutation analogues that work in
// either backend mode without depending on the Convex provider).
// ---------------------------------------------------------------------------

/** Subscribe to a query, re-fetching whenever the store notifies or deps change. */
export function useApiQuery<T>(
  fetcher: () => Promise<T>,
  depsKey: string,
): T | undefined {
  const [data, setData] = useState<T | undefined>(undefined);
  const fetcherRef = useRef(fetcher);
  fetcherRef.current = fetcher;

  const refetch = useCallback(() => {
    fetcherRef
      .current()
      .then((d) => setData(() => d))
      .catch(() => setData(undefined));
  }, []);

  useEffect(() => {
    refetch();
    return subscribeToStore(refetch);
  }, [refetch, depsKey]);

  return data;
}

/** Stable mutation wrapper (the fn may be recreated on each render). */
export function useApiMutation<Args, R = unknown>(
  fn: (args: Args) => Promise<R>,
): (args: Args) => Promise<R> {
  const fnRef = useRef(fn);
  fnRef.current = fn;
  return useCallback((args: Args) => fnRef.current(args), []);
}
