/**
 * Convex Auth bridge.
 *
 * Talks to the `auth` functions that @convex-dev/auth deploys (sign-in actions
 * + the `loggedIn` query), persists the session token in localStorage, and
 * exposes the same contract as the mock auth backend — so `src/lib/auth.tsx`
 * works unchanged in either backend mode.
 */
import { api } from "../../convex/_generated/api"; // real one, generated by `npx convex dev`
import { getConvexHttpClient } from "./backend-client";
import type { AuthUser } from "./types";

const TOKEN_KEY = "mik:convex-auth-token";

let pendingEmail: string | null = null;

function readToken(): string | null {
  try {
    return localStorage.getItem(TOKEN_KEY);
  } catch {
    return null;
  }
}

function writeToken(token: string | null): void {
  try {
    if (token) localStorage.setItem(TOKEN_KEY, token);
    else localStorage.removeItem(TOKEN_KEY);
  } catch {
    // storage unavailable — session simply won't persist
  }
}

function toAuthUser(u: unknown): AuthUser | null {
  if (!u || typeof u !== "object") return null;
  const user = u as { name?: string; email?: string; isAnonymous?: boolean };
  return {
    name: user.name,
    email: user.email,
    isGuest: user.isAnonymous ?? (!user.email && user.name === "Guest"),
  };
}

/** Result shape of the `auth.signIn` action (from @convex-dev/auth). */
interface SignInResult {
  tokens?: { token: string } | null;
  signingIn?: boolean;
}

export const convexAuth = {
  /** Restore a persisted session (no-op when absent). */
  init(): void {
    const token = readToken();
    if (token) {
      try {
        getConvexHttpClient().setAuth(token);
      } catch {
        // convex not configured — nothing to restore
      }
    }
  },

  async getUser(): Promise<AuthUser | null> {
    const token = readToken();
    if (!token) return null;
    try {
      getConvexHttpClient().setAuth(token);
      const user = await getConvexHttpClient().query(api.requireUser.me, {});
      return toAuthUser(user);
    } catch {
      return null;
    }
  },

  async signInAnonymous(): Promise<AuthUser> {
    const res = (await getConvexHttpClient().action(api.auth.signIn, {
      provider: "anonymous",
      params: {},
    })) as SignInResult | null;
    const token = res?.tokens?.token;
    if (!token) throw new Error("Guest sign-in failed");
    writeToken(token);
    getConvexHttpClient().setAuth(token);
    const user = await this.getUser();
    if (!user) throw new Error("Guest sign-in failed");
    return user;
  },

  async requestEmailOtp(email: string): Promise<void> {
    pendingEmail = email;
    await getConvexHttpClient().action(api.auth.signIn, {
      provider: "email-otp",
      params: { email },
    });
    // Success here only means "no immediate error" — the code arrives by email.
  },

  async verifyEmailOtp(code: string): Promise<AuthUser> {
    if (!pendingEmail) {
      throw new Error("No email to verify — start the sign-in again.");
    }
    const res = (await getConvexHttpClient().action(api.auth.signIn, {
      provider: "email-otp",
      params: { email: pendingEmail, code },
    })) as SignInResult | null;
    const token = res?.tokens?.token;
    if (!token) throw new Error("The verification code you entered is incorrect.");
    writeToken(token);
    getConvexHttpClient().setAuth(token);
    pendingEmail = null;
    const user = await this.getUser();
    if (!user) throw new Error("Sign-in failed after verification.");
    return user;
  },

  async signOut(): Promise<void> {
    try {
      await getConvexHttpClient().action(api.auth.signOut, {});
    } catch {
      // clear locally regardless
    }
    writeToken(null);
    try {
      getConvexHttpClient().clearAuth();
    } catch {
      // client may not exist in this mode
    }
  },
};
