/**
 * Convex-backed implementation of the MikApi contract.
 *
 * Lives in its own chunk so the Convex client libraries (convex/browser +
 * the generated API) are only downloaded when the app actually runs with
 * VITE_BACKEND=convex — and even then only after first use (see api.ts).
 */
import { api } from "../../convex/_generated/api"; // generated by `npx convex dev`
import { getConvexHttpClient } from "./backend-client";
import { convexAuth } from "./convex-auth";
import { notifyStoreChange } from "./store-events";
import type { MikApi } from "./api-types";
import type {
  Comment,
  Recording,
  Surah,
} from "./types";

export const convexApi: MikApi = {
  getUser: () => convexAuth.getUser(),
  signInAnonymous: () => convexAuth.signInAnonymous(),
  requestEmailOtp: (email) => convexAuth.requestEmailOtp(email),
  verifyEmailOtp: (code, email) => convexAuth.verifyEmailOtp(code, email),
  signOut: () => convexAuth.signOut(),

  async listSurahs() {
    const rows = await getConvexHttpClient().query(api.surahs.list, {});
    return rows as unknown as Surah[];
  },
  async getSurah(number) {
    const res = await getConvexHttpClient().query(api.surahs.getSurah, {
      number,
    });
    return res ? (res.surah as unknown as Surah) : null;
  },
  async seedSurahList() {
    await getConvexHttpClient().action(api.surahs.seedSurahList, {});
  },
  async seedSurah(args) {
    await getConvexHttpClient().action(api.surahs.seedSurah, args);
  },

  async listPracticed() {
    return getConvexHttpClient().query(api.surahs.listPracticed, {});
  },
  async togglePracticed(args) {
    await getConvexHttpClient().mutation(api.surahs.toggleAyahPracticed, args);
    notifyStoreChange();
  },

  async myRecordings() {
    const rows = await getConvexHttpClient().query(api.content.myRecordings, {});
    return rows as unknown as Recording[];
  },
  async courseRecordings(args) {
    const rows = await getConvexHttpClient().query(
      api.content.courseRecordings,
      args,
    );
    return rows as unknown as Recording[];
  },
  async generateUploadUrl() {
    return getConvexHttpClient().mutation(api.content.generateUploadUrl, {});
  },
  async saveRecording(input) {
    // Cast at the boundary: the UI passes plain strings; the generated API
    // expects Convex's branded Id types.
    const id = await getConvexHttpClient().mutation(
      api.content.saveRecording,
      input as any,
    );
    return id as unknown as string;
  },
  async deleteRecording(args) {
    await getConvexHttpClient().mutation(api.content.deleteRecording, {
      id: args.id as any,
    });
    notifyStoreChange();
  },

  async listComments(args) {
    const rows = await getConvexHttpClient().query(api.content.comments, args);
    return rows as unknown as Comment[];
  },
  async addComment(args) {
    await getConvexHttpClient().mutation(api.content.addComment, args);
    notifyStoreChange();
  },

  async quizBest(args) {
    const row = await getConvexHttpClient().query(api.content.quizBest, args);
    return row ? { score: row.score, total: row.total } : null;
  },
  async quizSummary() {
    const res = await getConvexHttpClient().query(api.content.quizSummary, {});
    return {
      taken: res.taken,
      best: res.best
        ? { score: res.best.score, total: res.best.total }
        : undefined,
    };
  },
  async saveQuizResult(args) {
    await getConvexHttpClient().mutation(api.content.saveQuizResult, args);
    notifyStoreChange();
  },
};
